### ISSUE TITLE
npm install on mac fails for fs-xattr@ 0.1.13

### ISSUE THREAD

**Issue by juturu** [LinusU/fs-xattr#11]
`> fs-xattr@0.1.13 install /Users/node_modules/appdmg/node_modules/fs-xattr
> node-gyp rebuild
2016-05-03T17:30:39.366Z: 
2016-05-03T17:30:40.664Z: child_process: customFds option is deprecated, use stdio instead.
2016-05-03T17:30:44.469Z:   CXX(target) Release/obj.target/xattr/src/async.o
2016-05-03T17:30:45.155Z: ../src/async.cc:43:19: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
2016-05-03T17:30:45.161Z:   int errorNumber = 0;
2016-05-03T17:30:45.161Z:                   ^
2016-05-03T17:30:45.188Z: ../src/async.cc:26:16: error: use of undeclared identifier 'nullptr'
2016-05-03T17:30:45.188Z:     callback = nullptr;
2016-05-03T17:30:45.188Z:                ^
2016-05-03T17:30:45.188Z:  warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
2016-05-03T17:30:45.188Z:   std::string *filename = nullptr;
2016-05-03T17:30:45.188Z:                         ^
2016-05-03T17:30:45.188Z: warning: in-class initialization of non-static data member is a C++11 extension [-Wc++11-extensions]
2016-05-03T17:30:45.189Z:   std::string *attribute = nullptr;`

**Comment by LinusU** [comment]
Hey, thank you for reporting this, I'm looking at it right now 👌

**Comment by LinusU** [comment]
@juturu Hmm, it seems that the actual error is `error: use of undeclared identifier 'nullptr'` which seems to imply that you aren't using a C++11 compatible compiler.

Did version 0.1.12 work for you (check with `npm install fs-xattr@0.1.12`)?

Which version of clang are you using (check with `clang --version`)?

Could you try out the test-11 branch that I just made (`npm install LinusU/fs-xattr#test-11`)?

After you have done the above steps, can you try and update your xcode command line tools to the latest version, and see if that helps (`xcode-select --install`)?

**Comment by vampserv** [comment]
`npm install fs-xattr` failed with same error as @juturu for me, while `npm install LinusU/fs-xattr#test-11` and `npm install fs-xattr@0.1.12` worked. my xcode cli tools were already at the latest.

**Comment by LinusU** [comment]
Hmm, interesting, which version of OS X are you on? And could you check which version of XCode you have installed?

**Comment by vampserv** [comment]
im on `OSX 10.11.4` and `Xcode 7.3.1`.

**Comment by LinusU** [comment]
Hmm, I'm also on OS X 10.11.4 and I'm using XCode 7.3... Cannot for the life of me figure out what this is...

Oh actually, which version of Node.js are you running?

**Comment by vampserv** [comment]
Looks like it is working on v4.4.3, but not 0.12.0.

**Comment by LinusU** [comment]
That's probably the culprit, I'll release a more compatible version shortly

**Comment by LinusU** [comment]
Fixed in 0.1.14
