### ISSUE TITLE
Fails to build with nan@1.5.1

### ISSUE THREAD

**Issue by byronclark** [LinusU/fs-xattr#6]
> fs-xattr@0.1.4 install /Users/bclark/sandbox/node_modules/fs-xattr
> node-gyp rebuild

  CXX(target) Release/obj.target/xattr/src/xattr.o
In file included from ../src/xattr.cc:3:
In file included from ../node_modules/nan/nan.h:63:
../node_modules/nan/nan_new.h:184:10: error: call to 'New' is ambiguous
  return NanIntern::Factory<T>::New(arg0);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~
../src/xattr.cc:60:52: note: in instantiation of function template specialization 'NanNew<v8::Integer, long>' requested here
  Handle<Value> constructorArgs[3] = { slowBuffer, NanNew<Integer>(valueLen), NanNew<Integer>(0) };
                                                   ^
../node_modules/nan/nan_new.h:86:26: note: candidate function
  static inline return_t New(int32_t value);
                         ^
../node_modules/nan/nan_new.h:87:26: note: candidate function
  static inline return_t New(uint32_t value);
                         ^
1 error generated.
make: *** [Release/obj.target/xattr/src/xattr.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2

**Comment by byronclark** [comment]
Looks like this is fixed in #5

**Comment by LinusU** [comment]
Try `0.1.5`
